export default class EventModel {

  public sponsorTier1Name: string = '';
  public sponsorTier2Name: string = '';
  public sponsorTier3Name: string = '';
  public receiptSubject: string = '';
  public receiptContent: string = '';
  public id: string = '';
  public name: string = '';
  public status: string = 'DRAFT';
  public slug: string = '';
  public venueName: string = '';
  public venueAddress: any = {};
  public eventStart: string = '';
  public eventEnd: string = '';
  public webUrl: string = '';
  public capacity: number = 0;
  public hostName: string = '';
  public hostEmail: string = '';
  public summary: string = '';
  public description: string = '';
  public terms: string = '';
  public ticketStart: string = '';
  public ticketEnd: string = '';
  public posterMode: string = 'NONE';
  public posterUrl: string = '';
  public coverImageUrl: string = '';
  public mainLogoImageUrl: string = '';
  public footerLogoImageUrl: string = '';
  public emailLogoImageUrl: string = '';
  public receiptLogoImageUrl: string = '';
  public enableBranding: boolean = false;
  public enableCheckoutDonation: boolean = false;
  public enableBuyerClaimAll: boolean = false;
  public enablePublicGuestList: boolean = false;
  public enableTax: boolean = false;
  public footerBgColor: string = '';
  public buttonText: string = '';
  public buttonTextColor: string = '';
  public buttonBgColor: string = '';
  public taxRate: number = 0;
  public taxNumber: string = '';
  public isPrivate: boolean = false;
  public cartTimeoutSeconds: number = 0;
  public embedId: string = '';
  public campaignId: string = '';
  public p2pProgramId: string = '';
  public lastConfigurationStep: string = '';
  public sendTicketsWithConfirmationEmail: boolean = false;
  public promoCodes: any = [];
  public emailSubscribers: any = [];
  public surveys: any = [];
  public sponsorTiers: any = [];
  public guestDetailsSettings: any = [];
  public ticketEmbedSettings?: any = {};
}

  // ticketStart ticketEnd isPrivate posterMode
